

theme: just-the-docs

title: Open Integration Hub
description: Open Source Integration Framework

url: 'https://weberjm.github.io/'
baseurl: '/openintegrationhub.github.io'
aux_links:
  'Open Integration Hub on GitHub':
    - '//github.com/openintegrationhub'

footer_content: 'Copyright &copy; 2021 <a href="https://cloudecosystem.org">Cloud Ecosystem e.V.</a>'

whitelist: 
  - "jekyll-seo-tag"
